alter table account_info add column pre_user_grp_id varchar(200);
alter table app_conf_info add column pre_user_grp_id varchar(200);
alter table app_conf_val_info add column pre_user_grp_id varchar(200);
alter table auto_report_info add column pre_user_grp_id varchar(200);
alter table client_info add column pre_user_grp_id varchar(200);
alter table configuration_settings add column pre_user_grp_id varchar(200);
alter table group_info add column pre_user_grp_id varchar(200);
alter table group_message_info add column pre_user_grp_id varchar(200);
alter table project_activity_info add column pre_user_grp_id varchar(200);
alter table project_comments add column pre_user_grp_id varchar(200);
alter table project_info add column pre_user_grp_id varchar(200);
alter table project_subteam_info add column pre_user_grp_id varchar(200);
alter table project_team_info add column pre_user_grp_id varchar(200);
alter table recurring_prj_info add column pre_user_grp_id varchar(200);
alter table task_info add column pre_user_grp_id varchar(200);
alter table user_activity_info add column pre_user_grp_id varchar(200);
alter table user_group_item add column pre_user_grp_id varchar(200);
alter table user_info add column pre_user_grp_id varchar(200);
alter table user_task_activity_info add column pre_user_grp_id varchar(200);
alter table user_usage_activity_info add column pre_user_grp_id varchar(200);
update account_info set pre_user_grp_id=user_grp_id;
update app_conf_info set pre_user_grp_id=user_grp_id;
update app_conf_val_info set pre_user_grp_id=user_grp_id;
update auto_report_info set pre_user_grp_id=user_grp_id;
update client_info set pre_user_grp_id=user_grp_id;
update configuration_settings set pre_user_grp_id=user_grp_id;
update group_info set pre_user_grp_id=user_grp_id;
update group_message_info set pre_user_grp_id=user_grp_id;
update project_activity_info set pre_user_grp_id=user_grp_id;
update project_comments set pre_user_grp_id=user_grp_id;
update project_info set pre_user_grp_id=user_grp_id;
update project_subteam_info set pre_user_grp_id=user_grp_id;
update project_team_info set pre_user_grp_id=user_grp_id;
update recurring_prj_info set pre_user_grp_id=user_grp_id;
update task_info set pre_user_grp_id=user_grp_id;
update user_activity_info set pre_user_grp_id=user_grp_id;
update user_group_item set pre_user_grp_id=user_grp_id;
update user_info set pre_user_grp_id=user_grp_id;
update user_task_activity_info set pre_user_grp_id=user_grp_id;
update user_usage_activity_info set pre_user_grp_id=user_grp_id;
update account_info set user_grp_id=1003 where user_grp_id=1004 ;
update app_conf_info set user_grp_id=1003 where user_grp_id=1004 ;
update app_conf_val_info set user_grp_id=1003 where user_grp_id=1004 ;
update auto_report_info set user_grp_id=1003 where user_grp_id=1004 ;
update client_info set user_grp_id=1003 where user_grp_id=1004 ;
update configuration_settings set user_grp_id=1003 where user_grp_id=1004 ;
update group_info set user_grp_id=1003 where user_grp_id=1004 ;
update group_message_info set user_grp_id=1003 where user_grp_id=1004 ;
update project_activity_info set user_grp_id=1003 where user_grp_id=1004 ;
update project_comments set user_grp_id=1003 where user_grp_id=1004 ;
update project_info set user_grp_id=1003 where user_grp_id=1004 ;
update project_subteam_info set user_grp_id=1003 where user_grp_id=1004 ;
update project_team_info set user_grp_id=1003 where user_grp_id=1004 ;
update recurring_prj_info set user_grp_id=1003 where user_grp_id=1004 ;
update task_info set user_grp_id=1003 where user_grp_id=1004 ;
update user_activity_info set user_grp_id=1003 where user_grp_id=1004 ;
update user_group_item set user_grp_id=1003 where user_grp_id=1004 ;
update user_info set user_grp_id=1003 where user_grp_id=1004 ;
update user_task_activity_info set user_grp_id=1003 where user_grp_id=1004 ;
update user_usage_activity_info set user_grp_id=1003 where user_grp_id=1004 ;

delete from user_group_item where user_grp_id=1004 ;

alter table user_task_activity_info add column pre_duration int(11);
update user_task_activity_info set pre_duration=duration;
update user_task_activity_info set duration=0 where duration < 0;
