Insert into DELIVERY_INTERFACE.USER_INFO (USER_ID,HASHKEY,PASSWORD,USER_ROLE) values ('admin','BM7-5BjYdhCkFUrhOf-0p0qrAx8cVLNl','1GOPbCCKZlGolkKrnN8ZDQ==','ADMIN');
Insert into DELIVERY_INTERFACE.USER_INFO (USER_ID,HASHKEY,PASSWORD,USER_ROLE) values ('manager','))$Oswj=wPphUlbd(Tfb@bah)0-@o^Nd','D4a5+iEZCIQCn+PnrOxSow==','MANAGER');
Insert into DELIVERY_INTERFACE.USER_INFO (USER_ID,HASHKEY,PASSWORD,USER_ROLE) values ('support','HuSvOR=hA-q+lR)=f&t8(+zu6H%Sa^(A','c1coTl/2jfmlGZ+fIcL89Q==','SUPPORT');
Insert into DELIVERY_INTERFACE.USER_INFO (USER_ID,HASHKEY,PASSWORD,USER_ROLE) values ('analyst','w-TG($y7=uxxOb7tcnV@nU1009qawZcR','W7yQVqDtZXP4WN9SPKV7HA==','ANALYST');
