package com.famstack.projectscheduler.contants;

public enum NotificationType
{
    USER_REGISTRAION,
    USER_UPDATE,
    RESET_PASSWORD,
    PROJECT_CREATE,
    PROJECT_UPDATE,
    PROJECT_DELETE,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_CREATED_ASSIGNED,
    TASK_ASSIGNED,
    TASK_CLOSED,
    TASK_COMPLETED,
    TASK_INPROGRESS,
    FORGOT_PASSWORD,
    PROJECT_COMMENT_ADDED,
    TASK_DEADLINE_MISSED,
    TASK_END_REMINDER,
    TASK_START_REMINDER,
    PROJECT_END_REMINDER,
    PROJECT_START_REMINDER,
    PROJECT_DEADLINE_MISSED,
    TASK_RE_ASSIGNED,
    TASK_AUTO_PAUSED,
    USER_ACTIVITY_REPORT,
    USER_UTILIZATION_REPORT, 
    USER_ACTIVITY_REPORT_DEFAULTER,
    USER_UTILIZATION_REPORT_DEFAULTER,
    WEEKWISE_USER_UTILIZATION_MONTHLY,
    WEEKWISE_USER_UTILIZATION_MONTHLY_DEFAULTER, 
    WEEKLY_PO_ESTIMATION_REPORT

}
