package com.famstack.projectscheduler.contants;

public enum ReportType {
	USER_SITE_ACTIVITY, 
	USER_UTILIZATION, 
	DAILYWISE_USER_UTILIZATION_WEEKLY, 
	WEEKWISE_USER_UTILIZATION_MONTHLY, 
	WEEKLY_PO_ESTIMATION,
	WEEKLY_PROJECT_HOURS
}
