package com.famstack.projectscheduler.contants;

public enum ReportType {
	USER_SITE_ACTIVITY, 
	USER_UTILIZATION, 
	DAILYWISE_USER_UTILIZATION_WEEKLY, 
	WEEKWISE_USER_UTILIZATION_MONTHLY,
	WEEKWISE_USER_UTILIZATION_MONTHLY_ENE,
	WEEKLY_PO_ESTIMATION,
	WEEKLY_PROJECT_HOURS,
	UTILIZATION_BY_SKILLS,
	UTILIZATION_BY_EMPLOYEE_BY_SKILLS,
	UTILIZATION_BY_EMPLOYEE_BY_PROJECT_CATEGORY;
}
